# -*- coding: utf-8 -*-
"""
Created on Thu Jun  9 03:36:11 2022

@author: Noah
"""

mid_term_profitable_trading_pairs = set(['LTCUSDT','QTUMUSDT','XLMUSDT','ONTUSDT','ICXUSDT','VETUSDT','HOTUSDT','ZILUSDT','FETUSDT','BATUSDT','IOSTUSDT','CELRUSDT','DASHUSDT','OMGUSDT','THETAUSDT','MITHUSDT','ATOMUSDT','ONEUSDT','DOGEUSDT','ANKRUSDT','WINUSDT','COSUSDT','DENTUSDT','CHZUSDT','RENUSDT','RVNUSDT','NKNUSDT','STXUSDT','KAVAUSDT','ARPAUSDT','OGNUSDT','LSKUSDT','BNTUSDT','LTOUSDT','STPTUSDT','SOLUSDT','CTSIUSDT','ARDRUSDT','MDTUSDT','REPUSDT','LRCUSDT','COMPUSDT','SNXUSDT','VTHOUSDT','DGBUSDT','DCRUSDT','STORJUSDT','MANAUSDT','BLZUSDT','KMDUSDT','SANDUSDT','OCEANUSDT','RSRUSDT','SUSHIUSDT','YFIIUSDT','KSMUSDT','UMAUSDT','UNIUSDT','OXTUSDT','AVAXUSDT','XVSUSDT','ALPHAUSDT','INJUSDT','UNFIUSDT','REEFUSDT','ASRUSDT','CELOUSDT','TWTUSDT','FIROUSDT','SFPUSDT','DODOUSDT','CAKEUSDT','DEGOUSDT','ALICEUSDT','PERPUSDT','EPSUSDT','AUTOUSDT','BTGUSDT','BARUSDT','FORTHUSDT','MASKUSDT','LPTUSDT','ATAUSDT','GTCUSDT','TORNUSDT','ERNUSDT','BONDUSDT','DEXEUSDT','CLVUSDT','QNTUSDT','FLOWUSDT','MINAUSDT','FARMUSDT','DYDXUSDT','IDEXUSDT','SYSUSDT','AGLDUSDT','RAREUSDT','ADXUSDT','AUCTIONUSDT','ENSUSDT','POWRUSDT','VGXUSDT','JASMYUSDT','PLAUSDT','PYRUSDT','RNDRUSDT','SANTOSUSDT','ACHUSDT','IMXUSDT','LOKAUSDT','ACAUSDT','XNOUSDT','ALPINEUSDT','KDAUSDT','BIFIUSDT','NEXOUSDT','LDOUSDT'])

short_term_profitable_trading_pairs = set(['ICXUSDT','ZILUSDT','FETUSDT','IOSTUSDT','OMGUSDT','ANKRUSDT','COCOSUSDT','CHZUSDT','RVNUSDT','ARPAUSDT','MDTUSDT','STMXUSDT','COMPUSDT','ZENUSDT','SNXUSDT','DGBUSDT','STORJUSDT','BLZUSDT','JSTUSDT','CRVUSDT','YFIIUSDT','KSMUSDT','UMAUSDT','AVAXUSDT','ALPHAUSDT','NEARUSDT','SKLUSDT','CELOUSDT','TWTUSDT','LPTUSDT','QNTUSDT','FLOWUSDT','MINAUSDT','FARMUSDT','MBOXUSDT','DYDXUSDT','DARUSDT','LOKAUSDT'])

long_term_profitable_trading_pairs = mid_term_profitable_trading_pairs.intersection(short_term_profitable_trading_pairs)

for i in long_term_profitable_trading_pairs:
    print(i)